// EL OPERADOR TERNARIO ES UNA FORMA CONCISA DE ESCRIBIR UNA DECLARACION CONDICIONAL

// ASIGNAR UN VALOR EN FUNCION DE QUE SE EVALUE UNA CONDICION
const edad = 14

// SE NOS CONFIRME SI SOMOS MAYORES DE EDAD
// SI ERES MAYOR DE 18, ERES MAYOR DE EDAD

const mensaje = (edad >= 18) ? "Eres mayor de edad" : "Eres menor de edad"
console.log(mensaje);